[project]
name = "reinforcinglearninglearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hihikyakya", email = "happyhippy20202020@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
]

[project.scripts]
reinforcinglearninglearning = "reinforcinglearninglearning:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
